### ISSUE TITLE
Is there a way to generate Custom Debugger Visualizer for 3rd Party assemblies?

### ISSUE THREAD

**Issue by JeremyThomas** [codingadventures/LINQBridgeVs#25]
I see you create DotNetDynamicVisualizerType.V12.0.dll for the BCL but what about other referenced assemblies?

**Comment by nbasakuragi** [comment]
Unfortunately there is no way to create custom debugger visualizers for 3rd party assemblies at the moment. It's something I could add as a new functionality. Although there could be problems for signed or obfuscated assemblies (if there are any). For this reason I map only types of the BCL whose are Serializable only as the assemblies containing the types (mscorlib etc) are all signed.

**Comment by JeremyThomas** [comment]
Would be good if you could add that ability, perhaps in the same dialog for generating visualizers for referenced projects.
From what I see you map non-Serializable types as well, or have I got that wrong?

**Comment by nbasakuragi** [comment]
yeah it would, I will consider that for my next release. I think it will be handy. 

I map non-Serializable type indeed, but since I need to inject the serializable attribute in every library (otherwise the binary-formatter won't work) I have to open-save, at compile time, all the assemblies and referenced libraries. 

In case of signed assemblies, which is the case of Microsoft's assemblies, I have to un-sign or re-sign them if the key is available. I just don't un-sign MS Assemblies to avoid changing any existing ms software.

**Comment by codingadventures** [comment]
this is going to be a big one, but worth a try.

**Comment by codingadventures** [comment]
Available in the next release
