### ISSUE TITLE
No magnifier glass

### ISSUE THREAD

**Issue by abukres** [codingadventures/LINQBridgeVs#30]
I installed the 2017 version. I enabled the bridge, set a breakpoint after an instance of my class was initialized, run it. I don't see a magnifying glass on the instance. I also created a string array and no magnifying.

It's not clear how the whole process works.  What do in the LinqPad? Is there something visible in there? Do we start using the same variable names as in the VS code?
 Appreciate a quick YouTube video where you are showing how it works.

**Comment by codingadventures** [comment]
Hi Abdu, that's a good idea, I will create a youtube video that explains the process along with some more detailed documentation. 

After you enable the bridge it is important you rebuild your solution (not just a build), so that the visualizers are created in the folder C:\Users\youruser\Documents\Visual Studio 2017\Visualizers

**Comment by Pavel-Malezhyk** [comment]
I have vs 2017 and 2012 on my computer.
After installing new release, vs 2012 works almost correctly (linqpad shows null instead some internal classes in collections), but in vs 2017 there is no magnifier glass

**Comment by codingadventures** [comment]
If you look at C:\Users\malejik\Documents\Visual Studio 2012\Visualizers you should see different dlls which are the debugger visualizers created for your Vs2012 solution. That's why the magnifier glass appears during a debugging session in VS 2012. 

If you only have attribcache140.bin in VS2017 visualizers folder it means no visualizers have been created. Those visualizers are created at compile time, when you rebuild your solution after you have bridge/activated it.

**Comment by Pavel-Malezhyk** [comment]
Thank you for answer! Of course bridge is activated and solution is rebuilt (even cleaned up and rebuilt), but my vs 2017 don't make visualizer dll's. How to debug it?)

**Comment by abukres** [comment]
There are no visualizers in that folder which belong to LINQBridgeVs. What's the name of visualizer file?

**Comment by codingadventures** [comment]
Hello guys,

I found the bug, please hold on, I'm about to release a new version

**Comment by codingadventures** [comment]
Hi,

I've release a new version 1.4.2 with the bug for Visual Studio 2017 fixed. Please uninstall LINQBridgeVs for VS2017 and re-install it again. Also please do delete the folder called _0_ located here:

**C:\Program Files (x86)\Microsoft Visual Studio\2017\0**

That was created by mistake by the previous extension.

**Comment by Pavel-Malezhyk** [comment]
Checked! Done .... Thank you!
