### ISSUE TITLE
No visualizers generated in VS2017 15.8 Preview 3

### ISSUE THREAD

**Issue by MikeStacey-Gee** [codingadventures/LINQBridgeVs#47]
I have rebuilt my solution several times, but the visualizer assemblies are not being generated. Are there any other VS2017 extensions that may be blocking the operation?

**Comment by codingadventures** [comment]
Hi, I doubt other extensions could conflict with this one but I can't exclude it for sure. The visualizer assembly generation is bound to the compilation process, so the problem lies either in the installation process or on the folder permissions --> Documents\Visual Studio 2017\Visualizers . 

One thing that could help me identify the issue is to have the log files (you have to enable logging in the option menu), Also if you could enable error reporting I would see the exceptions coming through in Sentry. 

Please check out the guide on how to enable logs and/or error reporting [here](https://github.com/codingadventures/LINQBridgeVs#bridgevs-option-menu)

**Comment by MikeStacey-Gee** [comment]
Will do

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeStacey-Gee** [comment]
Hi,

I have enabled error reporting and logging. After several rebuilds there is no log file.

Regards

Mike

**Comment by codingadventures** [comment]
That is very odd. I haven't got anything new either in Sentry. Please check the registry here **\HKEY_CURRENT_USER\Software\LINQBridgeVs** (refers to the section [How it works](https://github.com/codingadventures/LINQBridgeVs#how-it-works) in the readme). If the installation went well and also you bridged your solution correctly you should find in the registry your solution listed:
**\HKEY_CURRENT_USER\Software\LINQBridgeVs\15.0\Solutions\yoursolution** 

As a side note: which OS are you using? What type of solution are you trying to map (c#, vb, f#)

**Comment by codingadventures** [comment]
Hi,

I found out the problem. The preview version of Visual Studio install itself in **_C:\Program Files (x86)\Microsoft Visual Studio\Preview_** instead of _**C:\Program Files (x86)\Microsoft Visual Studio\2017**_ which is the default installation folder for Visual Studio 2017. Thus during the first configuration the relevant _.target_ files needed to override the MSBuild process don't end up in the correct folder. 

To fix this issue please copy the folder v15.0 and its content from _**C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\v15.0**_ to _**C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\v15.0**_

The next time the solution is rebuilt the visualizers are correctly generated

**Comment by MikeStacey-Gee** [comment]
Thank you for investigating, very much appreciated. This explains why it works on a remote VM in my office where the standard VS2017 is installed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by codingadventures** [comment]
Thanks for reporting the issue, I added a section in the README in case someone else has the same problem.
