### ISSUE TITLE
Bridge Solution button not working

### ISSUE THREAD

**Issue by kmataru** [codingadventures/LINQBridgeVs#61]
I had LinqPad5 installed long before, ran the configuration process but the _Bridge Solution_ button would not work, not even after VS restart.
I clicked on it several times, but it does nothing.

Any thoughts on this?

Not sure which info to include on this one:

* Visual Studio Enterprise 2017 (15.8.0)
* Windows 10

**Comment by codingadventures** [comment]
are they both greyed out in the BridgeVs menu? Have you completed the installation correctly by restarting with admin privileges?

if that's so, then I need to look at the logs and the registry to see why it doesn't work? Just for the record. Which type of solution are you trying to bridge? c#, vb?

**Comment by kmataru** [comment]
Nope. The _Bridge Solution_ is active and the other greyed out.
Visual Studio is set to run As Administrator every time.

There are only C# type projects in solution.

* Enable Logging: true

But no file is present under `C:\Users\[username]\AppData\Local\BridgeVs`...

PS: Even I setup the path of LinqPad to `D:\Program Files (x86)\LINQPad5`, in VS Options the Installation Path was `C:\Program Files (x86)\LINQPad5`, so I've changed it.

**Comment by codingadventures** [comment]
Sorry I might have missed the issue here. What do you mean by "Bridge Solution" would not work? you mean you press it and nothing happens? so I wonder you are not getting the message box after clicking on Bridge Solution.

It's weird logs are not available, but it can happen if something went wrong with the installation. 

if it doesn't work please open the registry and go to \HKEY_CURRENT_USER\Software\LINQBridgeVs, and delete LINQBridgeVs, uninstall the extension and try again with the installation. this time try to move LINQPad to the C: drive (I'm not sure having it in D would cause an issue).

**Comment by kmataru** [comment]
@codingadventures Thank you for your time!
This is my bad... Was hyped that I found such a great tool and misread the _Compatibility_ section.
We're using .NET Core projects. 🤦‍♂️ 

However, no _MessageBox_ was shown when clicking on "Bridge Solution".
